server {
  listen 80;
  server_name kopa.mkopaji.com;
  return 301 https://kopa.mkopaji.com$request_uri;
}

server {
  listen 443 ssl;
  server_name kopa.mkopaji.com;

  root /var/www/html/kopa-mkopaji/frontend;
  index index.html index.htm;

  ssl_certificate /etc/letsencrypt/live/kopa.mkopaji.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/kopa.mkopaji.com/privkey.pem;
  include /etc/letsencrypt/options-ssl-nginx.conf;
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

  location /api/ {
    proxy_pass http://localhost:3002;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_cache_bypass $http_upgrade;
    proxy_read_timeout 86400;
  }

  location = /health {
    proxy_pass http://localhost:3002;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location / {
    try_files $uri $uri.html $uri/ /index.html;
  }
}
